<a href="https://colab.research.google.com/github/susanlove77/AI_26-/blob/main/01_%EC%97%B0%EC%8A%B5%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [2]:
import numpy
print(numpy.array([1,2,3]))

[1 2 3]


In [6]:
import numpy as np

arr_1 = np.array([1,2,3,4,5]*2)
print(arr_1*2)

[ 2  4  6  8 10  2  4  6  8 10]


In [7]:
import numpy as np

arr_2 = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np

arr_3 = np.array([[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]],
                  [[13,14,15],
                   [16,17,18]]])
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [9]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1.dtype)

int64


In [10]:
import numpy as np

print(np.array([1,2,3]).dtype)

int64


In [11]:
import numpy as np

print(np.array([1,2,3],dtype='int8').dtype)

int8


In [12]:
print(np.array([1,2,3],dtype='i1').dtype)

int8


In [13]:
import numpy as np

ndarray_1= np.array([1,2,3]) # 넘파이 배열
ndarray_2 = np.array([4,5,6]) # 넘파이 배열
list_1 = [1,2,3] # 파이썬 리스트
list_2 = [4,5,6] # 파이썬 리스트

print(ndarray_1 + ndarray_2)
print(list_1+list_2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [15]:
import numpy as np

ndarray_1= np.array([1,2,3]) # 넘파이 배열
ndarray_2 = np.array([4,5,6]) # 넘파이 배열
list_1 = [1,2,3] # 파이썬 리스트
list_2 = [4,5,6] # 파이썬 리스트

result_list=[x+y for x, y in zip(list_1, list_2)]
print(result_list)

print(ndarray_1*2)
print(list_1*2)

[5, 7, 9]
[2 4 6]
[1, 2, 3, 1, 2, 3]


In [16]:
import numpy as np

a = np.array([2,3,4]) # 넘파이 정수형 배열 생성
print(a)  # 넘파이 배열 출력
print(a.dtype) # 넘파이 배열의 데이터 타입 출력
b=np.array([2.1, 3.2, 4.3]) # 넘파이 실수형 배열 생성
print(b)
print(b.dtype)

[2 3 4]
int64
[2.1 3.2 4.3]
float64


In [17]:
c = np.array(('i','j','k')) # 넘파이 문자열 배열 생성
print(c)
print(c.dtype)

['i' 'j' 'k']
<U1


In [18]:
d= np.array((True,True,False)) # 넘파이 논리형 배열 생성
print(d)
print(d.dtype)

[ True  True False]
bool


In [19]:
e=np.array(['ab','cd','e'],dtype='<U2') # 문자열 길이를 조절하여 배열 생성
print(e)
print(e.dtype)

['ab' 'cd' 'e']
<U2


In [21]:
import numpy as np

# a라는 변수에 (3,4) 크기의 넘파이 2차원 배열 생성
a=np.arange(12).reshape(3,4)
print(a)
print(a.shape) # 배열의 차원과 차원의 크기 반환
print(a.ndim) # 배열의 차원 수 반환
print(a.dtype) # 배열의 데이터 타입 반환
print(a.itemsize) # 배열의 각 요소의 크기를 바이트 단위로 반환
print(a.size) # 배열의 총 요소의 수 반환

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
int64
8
12


In [24]:
import numpy as np

# 각 학급에 4명의 학생, 각 학생이 3과목의 시험 점수를 가지고 있는 배열 생성
# 예시 : 3개의 학급, 각 학급에 4명의 학생, 각 학생당 국어, 영어, 수학 점수
scores = np.random.randint(0,101,size=(3,4,3))

# 학급별, 학생별, 과목별 점수를 출력
print("학급별 학생들의 점수 배열 (3차원 배열):")
print(scores)

# 학급, 학생, 과목별로 점수 출력
for class_idx in range(scores.shape[0]):
  print(f"\nClass {class_idx +1}")
  for student_idx in range(scores.shape[1]):
    korean, english, math = scores[class_idx, student_idx]
    print(f"Student {student_idx +1}-Korean:{korean}, English:{english},Math:{math}")

학급별 학생들의 점수 배열 (3차원 배열):
[[[ 18  85  33]
  [ 52  77  98]
  [ 86  40  74]
  [100  88  86]]

 [[ 98  71  17]
  [ 85  50  48]
  [ 76   5  49]
  [ 37  16  12]]

 [[ 96  36  70]
  [ 10  94  70]
  [ 48  11  92]
  [ 79 100   3]]]

Class 1
Student 1-Korean:18, English:85,Math:33
Student 2-Korean:52, English:77,Math:98
Student 3-Korean:86, English:40,Math:74
Student 4-Korean:100, English:88,Math:86

Class 2
Student 1-Korean:98, English:71,Math:17
Student 2-Korean:85, English:50,Math:48
Student 3-Korean:76, English:5,Math:49
Student 4-Korean:37, English:16,Math:12

Class 3
Student 1-Korean:96, English:36,Math:70
Student 2-Korean:10, English:94,Math:70
Student 3-Korean:48, English:11,Math:92
Student 4-Korean:79, English:100,Math:3


In [26]:
import numpy as np

#(3,4) 크기의 배열을 생성하여 0으로 채용
print(np.zeros((3,4,)))
#(3,4) 크기의 배열을 데이터 타입을 정수로 생성한 후, 0으로 채움
print(np.zeros((3,4),dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
import numpy as np

# np.ones(shape,[dtype]) # 예: np.ones((2,3,4))
print(np.ones((2,3,4),dtype=int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [32]:
import numpy as np

# np.empty(shape)
print(np.empty((2,3,)))

[[2.22502833e-315 0.00000000e+000 2.28716058e-315]
 [0.00000000e+000 6.01347002e-154 6.01334434e-154]]


In [35]:
import numpy as np

# 10이상 30미만까지 5 간격으로 생성
print(np.arange(10,30,5))
# 0이상 2미만까지 0.3 간격으로 생성
print(np.arange(start=0,stop=2,step=0.3))

# 1이상 10이하까지 값을 가진 크기 10짜리 배열 생성
print(np.linspace(start=1,stop=10,num=10,dtype=int))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
import numpy as np

# a와 b 배열 생성하여 출력
a=np.array([10,20,30,40])
b=np.arange(start=1,stop=5)
print(a)
print(b)

# 덧셈 연산
print(a+b)
# 뺄셈 연산
print(a-b)
# 곱셈 연산
print(a*b)
# 나눗셈 연산
print(a/b)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [37]:
# A와 B 배열 생성
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
# A * B : 요소별 곱셈 연산
print(A*B)
# A@B : 행렬 곱셈 사용
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [38]:
import numpy as np

# A와 B 배열 생성
A = np.array([1,2,3,4])
B = np.array([1,1,3,3])
# 비교 연산
print(A> B)
print(A==B)

[False  True False  True]
[ True False  True False]


In [40]:
import numpy as np

# 두명의 학생의 시험 점수를 배열로 생성합니다.
student1_scores = np.array([85,90,78]) # 학생1의 점수(국어, 영어, 수학)
student2_scores = np.array([92,88,95]) # 학생2의 점수(국어, 영어, 수학)

# 두 학생의 점수를 출력합니다.
print("학생 1의 점수:", student1_scores)
print("학생 2의 점수:", student2_scores)

# 두 학생의 총점을 구합니다.
total_scores=student1_scores + student2_scores
print("두 학생의 총점:", total_scores)

# 두 학생의 평균 점수를 구합니다.
average_scores = total_scores/2
print("두 학생의 평균 점수:",average_scores)

# 각 학생의 총점과 평균을 구합니다.
student1_total = np.sum(student1_scores)
student2_total = np.sum(student2_scores)
student1_average = np.mean(student1_scores)
student2_average = np.mean(student2_scores)

print("학생 1의 총점:",student1_total)
print("학생 1의 평균 점수:", student1_average)
print("학생 2의 총점:",student2_total)
print("학생 2의 평균 점수:",student2_average)

학생 1의 점수: [85 90 78]
학생 2의 점수: [92 88 95]
두 학생의 총점: [177 178 173]
두 학생의 평균 점수: [88.5 89.  86.5]
학생 1의 총점: 253
학생 1의 평균 점수: 84.33333333333333
학생 2의 총점: 275
학생 2의 평균 점수: 91.66666666666667


In [41]:
import numpy as np

# A 배열 생성
A = np.array([4,16,25])
# 제곱근 함수
print(np.sqrt(A))

[2. 4. 5.]


In [42]:
# a배열 생성& 출력
# 0부터 8미만까지 출력하고 (2,4)크기로 재가공하고 제곱하여 출력
a=np.arange(8).reshape(2,4)**2
print(a)

# 모든 요소의 합
print(a.sum())
# 모든 요소 중 평균
print(a.mean())
# 모든 요소 중 최솟값
print(a.min())
# 모든 요소 중 최댓값
print(a.max())
# 모든 요소의 누적합
print(a.cumsum())
# 모든 요소 중 최댓값의 인덱스
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


In [43]:
import numpy as np

# 0부터 8미만까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력
# a = array([[0,1,4,9],
#            [16,25,36,49]])
a =  np.arange(8).reshape(2,4)**2

# axis=0은 열기준으로 연산
print(a.mean(axis=0))
# axis=1은 행 기준으로 연산
print(a.max(axis=1))

[ 8. 13. 20. 29.]
[ 9 49]


In [45]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

# 인덱스가 0인, 인덱스가 3인 요소 출력
print(a[0])
print(a[3])

b = np.array([[0,1,2],[3,4,5]])
print(b)

# 인덱스가 [1,0]인, 인덱스가 [1,2]인 요소 출력
print(b[1,0])
print(b[1,2])

[0 1 2 3 4 5]
0
3
[[0 1 2]
 [3 4 5]]
3
5


In [46]:
import numpy as np

a= np.array([0,1,2,3,4,5])
print(a)

# 인덱스 0이상 인덱스 3미만 범위의 요소 출력
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [48]:
import numpy as np

a = np.arange(12).reshape(3,4,)
print(a)

# a>4 조건을 적용한 논리형 배열 생성
b= a>4
print(b)
print(a[b])
print(a[b].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
(7,)


In [49]:
import numpy as np

# 논리형 배열인 b를 이용하여 원본 a 배열의 값 변경하기(True인 값의 위치에 변경하기)
a[b]= 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [50]:
import numpy as np

a= np.array(['a','b','c','d','e','f','g','h'])
i =np.array([1,1,3,4])

# 배열 a에서 배열 i에 지정된 인덱스의 원소들을 출력
print(a[i])
j=np.array([[3,4],[5,6]])

# 배열 a에서 배열 j에 지정된 인덱스의 원소들을 출력
print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [51]:
b= np.array(['a','b','c','d'])
k=np.array([3,2,1,0])

# 배열 b에서 배열 k에 지정된 인덱스의 원소들을 재배열
b= b[k]
print(b)

['d' 'c' 'b' 'a']


In [52]:
import numpy as np

my_array = np.array([10,20,30,40,50])
subset=my_array[1:4] # 인덱스 1이상 4미만 추출 (4는 포함되지 않음)
print(subset) # 출력 : [20,30,40]

[20 30 40]


In [55]:
import numpy as np

# a 배열 생성
a= np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

# .reshape : 지정한 차원으로 변경하고 새로운 배열 변환
b = a.reshape(2,6)
print(b)
print(b.shape)

# 원본 a 배열은 기존의 (3,4) 형태 유지
print(a)
print(a.shape)

c= a.reshape(-1,3)
print(c)
print(c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
